modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="my_titan"
version="1.0.0"
displayName="My Titan"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="ARCADIA, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.my_titan]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.my_titan]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.my_titan]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.my_titan]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

